#!/usr/bin/env bash
set -euo pipefail

# hookd handler: issue_comment → claude command
# Responds to comment commands like:
#   /fix       - Claude analyzes and fixes the issue
#   /review    - Claude reviews the PR code
#   /ask <question> - Claude answers a question about the codebase
#
# Only triggers on comments starting with "/" to avoid noise.
# Runs inside an isolated git worktree (provided by hookd).
#
# Required env: HOOKD_GITHUB_TOKEN, HOOKD_REPO, HOOKD_ISSUE_NUMBER,
#               HOOKD_ISSUE_TITLE, HOOKD_COMMENT_BODY, HOOKD_COMMENT_USER,
#               HOOKD_WORKDIR

# Ensure gh CLI uses the hookd token for API calls and git push
export GH_TOKEN="${HOOKD_GITHUB_TOKEN:-}"

COMMENT="$HOOKD_COMMENT_BODY"
ISSUE_NUM="$HOOKD_ISSUE_NUMBER"

# Only process slash commands
if [[ ! "$COMMENT" =~ ^/ ]]; then
    echo "[hookd] Not a slash command, skipping"
    exit 0
fi

# Parse command
COMMAND=$(echo "$COMMENT" | head -1 | awk '{print $1}')
ARGS=$(echo "$COMMENT" | head -1 | sed 's|^/[a-z]* *||')

echo "[hookd] Command: $COMMAND from @${HOOKD_COMMENT_USER} on #${ISSUE_NUM}"

# React to the comment so user knows we saw it
gh api "repos/${HOOKD_REPO}/issues/comments/$(gh api "repos/${HOOKD_REPO}/issues/${ISSUE_NUM}/comments" --jq '.[-1].id')/reactions" \
    -f content='eyes' --silent 2>/dev/null || true

cd "$HOOKD_WORKDIR"

# Fetch latest and detect default branch
DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
git fetch origin "$DEFAULT_BRANCH" --quiet

case "$COMMAND" in
    /fix)
        # Create branch from latest origin, let claude fix, push PR
        BRANCH_NAME="hookd/fix-${ISSUE_NUM}-$(date +%s)"
        git checkout -b "$BRANCH_NAME" "origin/$DEFAULT_BRANCH" --quiet

        # Get the full issue context
        ISSUE_BODY=$(gh issue view "$ISSUE_NUM" --repo "$HOOKD_REPO" --json body --jq '.body')

        PROMPT="You are working on repo ${HOOKD_REPO}.

Issue #${ISSUE_NUM}: ${HOOKD_ISSUE_TITLE}

${ISSUE_BODY}

Additional instruction from @${HOOKD_COMMENT_USER}:
${ARGS:-Please fix this issue.}

Please implement the fix. Make sure tests pass. Commit with a message referencing #${ISSUE_NUM}."

        echo "[hookd] Claude is working on fixing #${ISSUE_NUM}..."
        claude --print "$PROMPT"

        if [ "$(git log "origin/$DEFAULT_BRANCH..HEAD" --oneline | wc -l)" -gt 0 ]; then
            git push -u origin "$BRANCH_NAME" --quiet
            gh pr create \
                --title "Fix #${ISSUE_NUM}: ${HOOKD_ISSUE_TITLE}" \
                --body "Fixes #${ISSUE_NUM} — triggered by @${HOOKD_COMMENT_USER} via \`/fix\`

$(git log "origin/$DEFAULT_BRANCH..HEAD" --pretty=format:'- %s')

*Generated by hookd + Claude*" \
                --base "$DEFAULT_BRANCH" \
                --head "$BRANCH_NAME"

            gh issue comment "$ISSUE_NUM" --repo "$HOOKD_REPO" \
                --body "PR created for this issue. See above."
        else
            gh issue comment "$ISSUE_NUM" --repo "$HOOKD_REPO" \
                --body "Claude analyzed the issue but didn't produce any code changes."
        fi
        ;;

    /review)
        # Review the PR diff
        PR_DIFF=$(gh pr diff "$ISSUE_NUM" --repo "$HOOKD_REPO" 2>/dev/null || echo "")
        if [ -z "$PR_DIFF" ]; then
            gh issue comment "$ISSUE_NUM" --repo "$HOOKD_REPO" \
                --body "No PR found for #${ISSUE_NUM} to review."
            exit 0
        fi

        PROMPT="Review this pull request diff for repo ${HOOKD_REPO}.
Focus on: correctness, edge cases, security, and style.
Be concise. Use GitHub-flavored markdown.

${ARGS:-}

\`\`\`diff
${PR_DIFF}
\`\`\`"

        REVIEW=$(claude --print "$PROMPT")
        gh issue comment "$ISSUE_NUM" --repo "$HOOKD_REPO" \
            --body "## Code Review by Claude

${REVIEW}

---
*Triggered by @${HOOKD_COMMENT_USER} via \`/review\`*"
        ;;

    /ask)
        # Answer a question about the codebase (worktree already has the code)
        PROMPT="You are answering a question about repo ${HOOKD_REPO}.

Context — Issue #${ISSUE_NUM}: ${HOOKD_ISSUE_TITLE}

Question from @${HOOKD_COMMENT_USER}:
${ARGS}"

        ANSWER=$(claude --print "$PROMPT")
        gh issue comment "$ISSUE_NUM" --repo "$HOOKD_REPO" \
            --body "${ANSWER}

---
*Answered by Claude via \`/ask\` — triggered by @${HOOKD_COMMENT_USER}*"
        ;;

    *)
        echo "[hookd] Unknown command: $COMMAND"
        ;;
esac
