#!/usr/bin/env bash
set -euo pipefail

# hookd handler: issue-opened → claude
# When a new issue is created, Claude automatically creates a branch,
# analyzes the issue, implements a fix, and opens a PR.
#
# Runs inside an isolated git worktree (provided by hookd).
#
# Required env: HOOKD_GITHUB_TOKEN, HOOKD_REPO, HOOKD_ISSUE_NUMBER,
#               HOOKD_ISSUE_TITLE, HOOKD_ISSUE_BODY, HOOKD_WORKDIR

echo "[hookd] New issue #${HOOKD_ISSUE_NUMBER}: ${HOOKD_ISSUE_TITLE}"

# Ensure gh CLI uses the hookd token for API calls and git push
export GH_TOKEN="${HOOKD_GITHUB_TOKEN:-}"

cd "$HOOKD_WORKDIR"

# Fetch latest and detect default branch
DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
git fetch origin "$DEFAULT_BRANCH" --quiet

# Create a feature branch from latest origin
BRANCH_NAME="hookd/issue-${HOOKD_ISSUE_NUMBER}"
git checkout -b "$BRANCH_NAME" "origin/$DEFAULT_BRANCH" --quiet

# Build the prompt for claude
PROMPT="You are working on repo ${HOOKD_REPO}.

GitHub Issue #${HOOKD_ISSUE_NUMBER}: ${HOOKD_ISSUE_TITLE}

${HOOKD_ISSUE_BODY}

Please:
1. Analyze this issue and understand what needs to be changed
2. Implement the fix or feature described
3. Make sure existing tests still pass
4. Commit your changes with a descriptive message referencing #${HOOKD_ISSUE_NUMBER}"

# Run claude in headless mode
echo "[hookd] Running claude to analyze and fix issue..."
claude --print "$PROMPT"

# Push and create PR if there are commits
if [ "$(git log "origin/$DEFAULT_BRANCH..HEAD" --oneline | wc -l)" -gt 0 ]; then
    git push -u origin "$BRANCH_NAME" --quiet

    PR_BODY="Automated fix for #${HOOKD_ISSUE_NUMBER}

## Issue
${HOOKD_ISSUE_TITLE}

## Changes
$(git log "origin/$DEFAULT_BRANCH..HEAD" --pretty=format:'- %s')

---
*Generated by [hookd](https://github.com/htlin222/hookd) + Claude*

Closes #${HOOKD_ISSUE_NUMBER}"

    gh pr create \
        --title "Fix #${HOOKD_ISSUE_NUMBER}: ${HOOKD_ISSUE_TITLE}" \
        --body "$PR_BODY" \
        --base "$DEFAULT_BRANCH" \
        --head "$BRANCH_NAME"

    echo "[hookd] PR created for issue #${HOOKD_ISSUE_NUMBER}"
else
    echo "[hookd] No changes made by claude for issue #${HOOKD_ISSUE_NUMBER}"
fi
