#!/usr/bin/env bash
set -euo pipefail

# hookd handler: push → run tests + auto-fix
# On push to the configured branch, runs tests.
# If tests fail, Claude attempts to fix them and pushes a fix commit.
#
# Runs inside an isolated git worktree (provided by hookd).
#
# Required env: HOOKD_GITHUB_TOKEN, HOOKD_REPO, HOOKD_BRANCH,
#               HOOKD_COMMIT_MESSAGES, HOOKD_WORKDIR

echo "[hookd] Push to ${HOOKD_BRANCH}: ${HOOKD_COMMIT_MESSAGES}"

# Ensure gh CLI uses the hookd token for API calls and git push
export GH_TOKEN="${HOOKD_GITHUB_TOKEN:-}"

cd "$HOOKD_WORKDIR"

# Fetch latest pushed state
git fetch origin "$HOOKD_BRANCH" --quiet
git checkout "origin/$HOOKD_BRANCH" --quiet

# Detect test runner
if [ -f "Makefile" ] && grep -q "^test:" Makefile; then
    TEST_CMD="make test"
elif [ -f "pyproject.toml" ]; then
    TEST_CMD="python -m pytest"
elif [ -f "package.json" ]; then
    TEST_CMD="npm test"
elif [ -f "Cargo.toml" ]; then
    TEST_CMD="cargo test"
else
    echo "[hookd] No test runner detected, skipping"
    exit 0
fi

echo "[hookd] Running: $TEST_CMD"

if $TEST_CMD; then
    echo "[hookd] Tests passed"
    exit 0
fi

echo "[hookd] Tests failed, asking Claude to fix..."

# Capture the failure output
FAILURE=$($TEST_CMD 2>&1 || true)

# Create a fix branch so we don't push directly
FIX_BRANCH="hookd/autofix-${HOOKD_BRANCH}-$(date +%s)"
git checkout -b "$FIX_BRANCH" --quiet

PROMPT="You are working on repo ${HOOKD_REPO}, branch ${HOOKD_BRANCH}.

The following test command failed after a recent push:
  $ ${TEST_CMD}

Test output:
\`\`\`
${FAILURE}
\`\`\`

Recent commits:
${HOOKD_COMMIT_MESSAGES}

Please fix the failing tests. Commit your fix."

claude --print "$PROMPT"

# If claude made fixes, push as PR instead of direct push
if [ "$(git log "origin/$HOOKD_BRANCH..HEAD" --oneline | wc -l)" -gt 0 ]; then
    git push -u origin "$FIX_BRANCH" --quiet
    gh pr create \
        --title "Fix failing tests on ${HOOKD_BRANCH}" \
        --body "Tests failed after a recent push. Claude analyzed the failure and applied a fix.

$(git log "origin/$HOOKD_BRANCH..HEAD" --pretty=format:'- %s')

*Generated by hookd + Claude*" \
        --base "$HOOKD_BRANCH" \
        --head "$FIX_BRANCH"
    echo "[hookd] PR created with test fix for ${HOOKD_BRANCH}"
else
    echo "[hookd] Claude could not fix the tests"
fi
